export { default as DONBOSCO_Detalles } from './DonBosco/DonBoscoDetalles'
export { default as DONBOSCO_Mapa } from './DonBosco/DonBoscoMap'
export { default as DONBOSCO_Actividades } from './DonBosco/DonBoscoAtividades'
export { default as DONBOSCO_Horarios } from './DonBosco/DonBoscoHorario'
export { default as DONBOSCO_Entradas } from './DonBosco/DonBoscoEntradas'

export { default as EXPOTEC_Detalles } from './Expotec/ExpotecDetalles'
export { default as EXPOTEC_Mapa } from './Expotec/ExpotecMap'
export { default as EXPOTEC_Actividades } from './Expotec/ExpotecActividades'
export { default as EXPOTEC_Horarios } from './Expotec/ExpotecHorarios'
export { default as EXPOTEC_Entradas } from './Expotec/ExpotecEntradas'
export { default as EXPOTEC_Expositores } from './Expotec/ExpotecExpositores'

export { default as MARIA_Detalles } from './Maria/MariaDetalles'
export { default as MARIA_Actividades } from './Maria/MariaActividades'
export { default as MARIA_Entradas } from './Maria/MariaEntradas'
export { default as MARIA_Horarios } from './Maria/MariaHorario'
export { default as MARIA_Mapa } from './Maria/MariaMap'
